Attribute VB_Name = "EnumModule"
Option Explicit

'The MIT License (MIT)
'
'Copyright (c) 2020 FORREST
' Mateusz Milewski mateusz.milewski@mpsa.com aka FORREST
'
'Permission is hereby granted, free of charge, to any person obtaining a copy
'of this software and associated documentation files (the "Software"), to deal
'in the Software without restriction, including without limitation the rights
'to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
'copies of the Software, and to permit persons to whom the Software is
'furnished to do so, subject to the following conditions:
'
'The above copyright notice and this permission notice shall be included in all
'copies or substantial portions of the Software.
'
'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
'IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
'FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
'AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
'LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
'OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
'SOFTWARE.
'
'
' THE EVO TOOL


Public Enum E_FILE_TYPE
    E_MASTER_PUS
    E_FEED_CPL
    E_TP04_01
    E_SQ01
    E_INTERROCOM
    E_MB51
End Enum

Public Enum E_MASTER_ORDER
    E_MASTER_Reference = 1
    E_MASTER_DESIGNATION
    E_MASTER_QTY
    E_MASTER_CQTY
    E_MASTER_ECHANCIER_ONL_S
    E_MASTER_cofor
    E_MASTER_Nom_fournisseur
    E_MASTER_prog_livraison
    E_MASTER_num_contrat
    E_MASTER_Nom_appro
    E_MASTER_Tel_appro
    E_MASTER_mail_appro
    E_MASTER_Nom_contact_log
    E_MASTER_Tel_contact_log
    E_MASTER_mail_contact_log
    E_MASTER_TMC
End Enum

Public Enum E_MASTER_2_ORDER
    E_MASTER_2_COFOR_VENDEUR = 17
    E_MASTER_2_COFOR_EXPEDITEUR
    E_MASTER_2_NOM_FOURNISSEUR
    E_MASTER_2_ADDRESS_EXPEDITEUR_COMPLET
    E_MASTER_2_COFOR_HIBRIDE
    E_MASTER_2_Incoterm
    E_MASTER_2_TYPE_DE_PIECE
    E_MASTER_2_CONDI
    E_MASTER_2_UC
    E_MASTER_2_POIDS
    E_MASTER_2_LONGEUR
    E_MASTER_2_LARGEUR
    E_MASTER_2_HAUTEUR
    E_MASTER_2_VOLUME
    E_MASTER_2_HAZARDOUS
    E_MASTER_2_STACKABLE
    E_MASTER_2_ALT_condi
    E_MASTER_2_ALT_poids
    E_MASTER_2_Alt_longueur
    E_MASTER_2_Alt_largeur
    E_MASTER_2_Alt_hauteur
    E_MASTER_2_COFOR_GEFCO
    E_MASTER_2_AGENCE_GEFCO
    E_MASTER_2_CONTACT_AGENCE
    E_MASTER_2_nom_contact_transport
    E_MASTER_2_tel_contact_transport
    E_MASTER_2_mail_contact_transport
    E_MASTER_2_DHEF
    E_MASTER_2_DHAS
    E_MASTER_2_No_Ordenes
    E_MASTER_2_ROUTE
    E_MASTER_2_ML
End Enum


Public Enum E_FORM_SCENARIO_TYPE
    E_FORM_SCENARIO_COPY_PASTE = 1
    E_FORM_SCENARIO_CREATE_PIVOT_SCENARIO
    E_FORM_SCENARIO_KPI
    E_FORM_SCENATIO_PRICE_MATCHING_FOR_TP04
    E_FORM_SCENATIO_PRICE_MATCHING_FOR_SQ01
End Enum


Public Enum E_COPY_HANDLER_INIT
    E_COPY_HANDLER_COPY_ONE = 1
    E_COPY_HANDLER_BY_TMC_OPT
    E_COPY_HANDLER_FOR_PIVOT_CREATION
End Enum


Public Enum E_PIVOT_SRC
    E_PIVOT_SRC_ID = 1
    E_PIVOT_SRC_WIERSZ
    E_PIVOT_SRC_REF
    E_PIVOT_SRC_COFOR_VENDEUR
    E_PIVOT_SRC_COFOR_EXPEDITEUR
    E_PIVOT_SRC_SUPPLIER_NAME
    E_PIVOT_SRC_DELIVERY_DATE
    E_PIVOT_SRC_DELIVERY_YEAR
    E_PIVOT_SRC_DELIVERY_MONTH
    E_PIVOT_SRC_DELIVERY_WEEK
    E_PIVOT_SRC_DELIVERY_YYYYCW
    E_PIVOT_SRC_AK_COL_FROM_PLE
    E_PIVOT_SRC_ORDER_DATE
    E_PIVOT_SRC_ORDER_YEAR
    E_PIVOT_SRC_ORDER_MONTH
    E_PIVOT_SRC_ORDER_WEEK
    E_PIVOT_SRC_ORDER_YYYYCW
    E_PIVOT_SRC_ROUTE
    E_PIVOT_SRC_PILOT
    E_PIVOT_SRC_ROUTE_AND_PILOT
    E_PIVOT_SRC_QTY
    E_PIVOT_SRC_CQTY
    E_PIVOT_SRC_UC
    E_PIVOT_SRC_OQ
    E_PIVOT_SRC_COQ
    E_PIVOT_SRC_ROUNDUP_OQ1
    E_PIVOT_SRC_ROUNDUP_COQ1
    E_PIVOT_SRC_SUMIF_QTY
    E_PIVOT_SRC_SUMIF_CQTY
    E_PIVOT_SRC_SUMIF_UC
    E_PIVOT_SRC_SUMIF_OQ
    E_PIVOT_SRC_SUMIF_COQ
    E_PIVOT_SRC_CONDI
    E_PIVOT_SRC_UA_PC_GV
    E_PIVOT_SRC_UA_BPC
    E_PIVOT_SRC_UA_MC
    E_PIVOT_SRC_UA_MBU
    E_PIVOT_SRC_UA_MAX_CAPACITY
    E_PIVOT_SRC__TN_ML
    E_PIVOT_SRC__CONFIRMED_TN_ML
    E_PIVOT_SRC__LQ
    E_PIVOT_SRC__CLQ
    E_PIVOT_SRC__RP
    E_PIVOT_SRC__CRP
    E_PIVOT_SRC__TN_box_ML
    E_PIVOT_SRC__CONFIRMED_TN_box_ML
    E_PIVOT_SRC__RN_ML
    E_PIVOT_SRC__CONFIRMED_RN_ML
    E_PIVOT_SRC__ROUNDUP_RN_ML
    E_PIVOT_SRC__ROUNDUP_CONFIRMED_RN_ML
    E_PIVOT_SRC___SHORT_ORDER_DATE
    E_PIVOT_SRC___SHORT_DEL_DATE
    E_PIVOT_SRC____TYPE_DE_PIECE
    E_PIVOT_SRC____CLOE_COL_E_PRICE
End Enum


Public Enum E_PIVOT_PROXY2
    E_PIVOT_PROXY2_ID = 1
    E_PIVOT_PROXY2_WIERSZ
    E_PIVOT_PROXY2_REF
    E_PIVOT_PROXY2_COFOR_VENDEUR
    E_PIVOT_PROXY2_COFOR_EXPEDITEUR
    E_PIVOT_PROXY2_SUPPLIER_NAME
    E_PIVOT_PROXY2_DELIVERY_DATE
    E_PIVOT_PROXY2_DELIVERY_YEAR
    E_PIVOT_PROXY2_DELIVERY_MONTH
    E_PIVOT_PROXY2_DELIVERY_WEEK
    E_PIVOT_PROXY2_DELIVERY_YYYYCW
    E_PIVOT_PROXY2_AK_COL_FROM_PLE
    E_PIVOT_PROXY2_ORDER_DATE
    E_PIVOT_PROXY2_ORDER_YEAR
    E_PIVOT_PROXY2_ORDER_MONTH
    E_PIVOT_PROXY2_ORDER_WEEK
    E_PIVOT_PROXY2_ORDER_YYYYCW
    E_PIVOT_PROXY2_ROUTE_AND_PILOT
    E_PIVOT_PROXY2_SUMIF_QTY
    E_PIVOT_PROXY2_SUMIF_CQTY
    E_PIVOT_PROXY2_SUMIF_UC
    E_PIVOT_PROXY2_SUMIF_OQ
    E_PIVOT_PROXY2_SUMIF_COQ
    E_PIVOT_PROXY2_CONDI
    E_PIVOT_PROXY2_UA_PC_GV
    E_PIVOT_PROXY2_UA_BPC
    E_PIVOT_PROXY2_UA_MC
    E_PIVOT_PROXY2_UA_MBU
    E_PIVOT_PROXY2_UA_MAX_CAPACITY
    E_PIVOT_PROXY2__TN_ML
    E_PIVOT_PROXY2__CONFIRMED_TN_ML
    E_PIVOT_PROXY2__LQ
    E_PIVOT_PROXY2__CLQ
    E_PIVOT_PROXY2__RP
    E_PIVOT_PROXY2__CRP
    E_PIVOT_PROXY2__TN_box_ML
    E_PIVOT_PROXY2__CONFIRMED_TN_box_ML
    E_PIVOT_PROXY2__RN_ML
    E_PIVOT_PROXY2__CONFIRMED_RN_ML
    E_PIVOT_PROXY2__ROUNDUP_RN_ML
    E_PIVOT_PROXY2__ROUNDUP_CONFIRMED_RN_ML
    E_PIVOT_PROXY2___SHORT_ORDER_DATE
    E_PIVOT_PROXY2___SHORT_DEL_DATE
    E_PIVOT_PROXY2____TYPE_DE_PIECE
    E_PIVOT_PROXY2____CLOE_COL_E_PRICE
End Enum



Public Enum E_KPI_SRC
    E_KPI_SRC_REF = 1
    E_KPI_SRC_V_COFOR
    E_KPI_SRC_E_COFOR
    E_KPI_SRC_SUPPLIER_NAME
    E_KPI_SRC_DAP
    E_KPI_SRC_NO_DATA
    E_KPI_SRC_TYPE_DE_PIECE
    E_KPI_SRC_UA
    E_KPI_SRC_PLE
    E_KPI_SRC_GREEN
    E_KPI_SRC_BLUE
    E_KPI_SRC_YELLOW
End Enum






Public Enum E_TP04_OUTPUT_REP_PART
    E_TP04_OUTPUT_REP_PART_PRESERIAL = E_MASTER_TMC + 1
    E_TP04_OUTPUT_REP_PART_INIT_SERIAL_PRICE
    E_TP04_OUTPUT_REP_PART_RATE
    E_TP04_OUTPUT_REP_PART_OKNOK
End Enum


Public Enum E_SQ01_CONFIG
    E_SQ01_CONFIG_MAKE_ALL
    E_SQ01_CONFIG_START_FROM_PASTING_ALREADY_PREPARED_INPUT_LIST
End Enum

'TP04_01

Public Enum E_TP04_01
    E_TP04_01_DOMAINE = 1
    E_TP04_01_ARTICLE
    E_TP04_01_REPERE_UTI
    E_TP04_01_DOC_ACHAT
    E_TP04_01_POSTE
    E_TP04_01_TYPE
    E_TP04_01_DIV
    E_TP04_01_FOUR
    E_TP04_01_DATE_DEBUT
    E_TP04_01_DATE_FIN
    E_TP04_01_UNITE_DE_PRIX
    E_TP04_01_PRIX
    E_TP04_01_UNITE
    E_TP04_01_DEV
End Enum

Public Enum E_FROM_SQ01_QUASI_TP04
    E_FROM_SQ01_QUASI_TP04_DOMAIN = 1
    E_FROM_SQ01_QUASI_TP04_ARTICLE
    E_FROM_SQ01_QUASI_TP04_RU
    E_FROM_SQ01_QUASI_TP04_DOC_ACHAT
    E_FROM_SQ01_QUASI_TP04_POSTE
    E_FROM_SQ01_QUASI_TP04_TYPE
    E_FROM_SQ01_QUASI_TP04_DIV
    E_FROM_SQ01_QUASI_TP04_FOUR
    E_FROM_SQ01_QUASI_TP04_DATE_DEBUT
    E_FROM_SQ01_QUASI_TP04_DATE_FIN
    E_FROM_SQ01_QUASI_TP04_UNITE
    E_FROM_SQ01_QUASI_TP04_SUM
    E_FROM_SQ01_QUASI_TP04_UNITE2_EMPTY
    E_FROM_SQ01_QUASI_TP04_CURRENCY
End Enum


Public Enum E_SQ01_PREDEF
    E_SQ01_PREDEF_SYSTEM
    E_SQ01_PREDEF_LIST1
    E_SQ01_PREDEF_STD1
    E_SQ01_PREDEF_LIST2
    E_SQ01_PREDEF_STD2
End Enum


Public Enum E_N_SUPPLIERS
    E_N_SUPPLIERS_COFOR = 1
    E_N_SUPPLIERS_PLT
    E_N_SUPPLIERS_TYPE
    E_N_SUPPLIERS_DESC
    E_N_SUPPLIERS_COCD
    E_N_SUPPLIERS_COMPANY
    E_N_SUPPLIERS_BU_ORDER
    E_N_SUPPLIERS_ONL_ORDER
    E_N_SUPPLIERS_CONT
    E_N_SUPPLIERS_DEL_SCHED
    E_N_SUPPLIERS_GA_C_RESP
    E_N_SUPPLIERS_GA_EXE_SECTOR
    E_N_SUPPLIERS_DGP_SGR
    E_N_SUPPLIERS_SIGAPP_SIGMA
    E_N_SUPPLIERS_PROTO_FLAG
    E_N_SUPPLIERS_PURCH_ORG
    E_N_SUPPLIERS_INT_EXT_VEN
End Enum



Public Enum E_ORDER_INTERROCOM
    INTERROCOM_article = 1
    INTERROCOM_GM
    INTERROCOM_Designation_achat
    INTERROCOM_Div
    INTERROCOM_Date_prix
    INTERROCOM_cofor
    INTERROCOM_Fournisseur
    INTERROCOM_GA
    INTERROCOM_Un
    INTERROCOM_s
    INTERROCOM_N_cde
    INTERROCOM_Type
    INTERROCOM_e
    INTERROCOM_prix
    INTERROCOM_Devise
    INTERROCOM_Base_de_prix
    INTERROCOM_Repartition
    INTERROCOM_N_DA
    INTERROCOM_Date_DA
    INTERROCOM_FNR_fab
    INTERROCOM_FNR_Exp
    INTERROCOM_N_poste
End Enum

Public Enum E_OUT_INTERROCOM
    E_OUT_INTERROCOM_A = 1
    E_OUT_INTERROCOM_COFOR
    E_OUT_INTERROCOM_DIV
    E_OUT_INTERROCOM_UN
    E_OUT_INTERROCOM_FINAL_PRIX
    E_OUT_INTERROCOM_REP
End Enum


Public Enum E_MB51_AUTO_DECISION_LAYOUT
    E_MB51_AUTO_DECISION_LAYOUT_0
    E_MB51_AUTO_DECISION_LAYOUT_NEW
    E_MB51_AUTO_DECISION_LAYOUT_PREV
End Enum


Public Enum E_ORDER_MB51_0
    E_MB51_0_ARTICLE = 1
    E_MB51_0_DESC
    E_MB51_0_DIV
    E_MB51_0_MAG
    E_MB51_0_CTRE_COUTS
    E_MB51_0_MVT
    E_MB51_0_DOC_ART
    E_MB51_0_LOT
    E_MB51_0_DATE_CPT
    E_MB51_0_DATE_SAISIE_LE
    E_MB51_0_DATE_PIECE
    E_MB51_0_SAISIE_A
    E_MB51_0_QTY
    E_MB51_0_UN
    E_MB51_0_UNX
    E_MB51_0_MONTANT_DI
    E_MB51_0_DEVISE
    E_MB51_0_ORDRE
    E_MB51_0_REF
    E_MB51_0_CDE_ACHAT
    E_MB51_0_FOUR
    E_MB51_0_PCS_PRICE
    E_MB51_0_EXT_PCS_PRICE
    E_MB51_0_EXT_PCS_PRICE_CURR
    E_MB51_0_EXT_USED_RATE
    E_MB51_0_EXT_PCS_PRICE_IN_EUR
    E_MB51_0_IS_WITH_INDEX
    E_MB51_0_IS_CANCELLED
    E_MB51_0_IS_INTERNAL
    E_MB51_0_IS_IN_TANGO
    E_MB51_0_TANGO_PCS_PRICE
    E_MB51_0_CW
    E_MB51_0_MANAGER_DA
    E_MB51_0_RU
End Enum




Public Enum E_ORDER_MB51_NEW
    E_MB51_NEW_MVT = 1
    E_MB51_NEW_S
    E_MB51_NEW_TXTE
    E_MB51_NEW_CDE_ACHAT
    E_MB51_NEW_ARTICLE
    E_MB51_NEW_DESC
    E_MB51_NEW_QTY
    E_MB51_NEW_MONTANT_DI
    E_MB51_NEW_DEVISE
    E_MB51_NEW_UNX
    E_MB51_NEW_DIV
    E_MB51_NEW_MAG
    E_MB51_NEW_FOUR
    E_MB51_NEW_LOT
    E_MB51_NEW_DATE_SAISIE_LE
    E_MB51_NEW_SAISIE_A
    E_MB51_NEW_DATE_PIECE
    E_MB51_NEW_REF
    E_MB51_NEW_PCS_PRICE
    E_MB51_NEW_EXT_PCS_PRICE
    E_MB51_NEW_EXT_PCS_PRICE_CURR
    E_MB51_NEW_EXT_USED_RATE
    E_MB51_NEW_EXT_PCS_PRICE_IN_EUR
    E_MB51_NEW_IS_WITH_INDEX
    E_MB51_NEW_IS_CANCELLED
    E_MB51_NEW_IS_INTERNAL
    E_MB51_NEW_IS_IN_TANGO
    E_MB51_NEW_TANGO_PCS_PRICE
    E_MB51_NEW_CW
    E_MB51_NEW_MANAGER_DA
    E_MB51_NEW_RU
End Enum




Public Enum E_ORDER_MB51_PREV
    E_MB51_PREV_ARTICLE = 1
    E_MB51_PREV_DESC
    E_MB51_PREV_DIV
    E_MB51_PREV_MAG
    E_MB51_PREV_CTRE_COUTS
    E_MB51_PREV_MVT
    E_MB51_PREV_DOC_ART
    E_MB51_PREV_LOT
    E_MB51_PREV_DATE_CPT
    E_MB51_PREV_DATE_SAISIE_LE
    E_MB51_PREV_DATE_PIECE
    E_MB51_PREV_SAISIE_A
    E_MB51_PREV_QTY
    E_MB51_PREV_UN
    E_MB51_PREV_UNX
    E_MB51_PREV_MONTANT_DI
    E_MB51_PREV_DEVISE
    E_MB51_PREV_ORDRE
    E_MB51_PREV_REF
    E_MB51_PREV_CDE_ACHAT
    E_MB51_PREV_FOUR
    E_MB51_PREV_PCS_PRICE
    E_MB51_PREV_EXT_PCS_PRICE
    E_MB51_PREV_EXT_PCS_PRICE_CURR
    E_MB51_PREV_EXT_USED_RATE
    E_MB51_PREV_EXT_PCS_PRICE_IN_EUR
    E_MB51_PREV_IS_WITH_INDEX
    E_MB51_PREV_IS_CANCELLED
    E_MB51_PREV_IS_INTERNAL
    E_MB51_PREV_IS_IN_TANGO
    E_MB51_PREV_TANGO_PCS_PRICE
    E_MB51_PREV_CW
End Enum


Public Enum E_ADJUSTED_SQ01
    E_ADJUSTED_SQ01_Reference = 1
    E_ADJUSTED_SQ01_designation
    E_ADJUSTED_SQ01_QUANTITE_T
    E_ADJUSTED_SQ01_QUANTITE_CONF
    E_ADJUSTED_SQ01_CW
    E_ADJUSTED_SQ01_COFOR
    E_ADJUSTED_SQ01_nomFournisseur
    E_ADJUSTED_SQ01_progLivraison
    E_ADJUSTED_SQ01_numero_contrat
    E_ADJUSTED_SQ01_Nom_appro
    E_ADJUSTED_SQ01_Tel_appro
    E_ADJUSTED_SQ01_mail_appro
    E_ADJUSTED_SQ01_Nom_contact_log
    E_ADJUSTED_SQ01_Tel_contact_log
    E_ADJUSTED_SQ01_mail_contact_log
    E_ADJUSTED_SQ01_TMC
    E_ADJUSTED_SQ01_PRE_SERIAL_PRICE_YPRS_contract
    E_ADJUSTED_SQ01_INITIAL_SERIAL_PRICE
    E_ADJUSTED_SQ01_RATE_PRE_SERIAL
    E_ADJUSTED_SQ01_OKNOK
    E_ADJUSTED_SQ01_WITH_INDEX
    E_ADJUSTED_SQ01_IS_INTERNAL
    E_ADJUSTED_SQ01_IS_IN_TANGO
    E_ADJUSTED_SQ01_TANGO_PCS_PRICE
    ' new one from 060
    E_ADJUSTED_SQ01_DOMAIN
    E_ADJUSTED_SQ01_RU
    E_ADJUSTED_SQ01_DIV
    ' 061
    E_ADJUSTED_SQ01_MANAGER_DA
End Enum



Public Enum E_FINAL_TOUCH_RECEPTION
    E_FINAL_TOUCH_RECEPTION_Mag = 1
    E_FINAL_TOUCH_RECEPTION_Mvt
    E_FINAL_TOUCH_RECEPTION_Designation_article
    E_FINAL_TOUCH_RECEPTION_Qte_UAc
    E_FINAL_TOUCH_RECEPTION_UAc
    E_FINAL_TOUCH_RECEPTION_Montant_di
    E_FINAL_TOUCH_RECEPTION_Dev
    E_FINAL_TOUCH_RECEPTION_article
    E_FINAL_TOUCH_RECEPTION_Date_cpt
    E_FINAL_TOUCH_RECEPTION_Fourn
    E_FINAL_TOUCH_RECEPTION_Cde_achat
    E_FINAL_TOUCH_RECEPTION_prix_Sigapp
    E_FINAL_TOUCH_RECEPTION_prix_Tango
    E_FINAL_TOUCH_RECEPTION_Ecart
    E_FINAL_TOUCH_RECEPTION_RU
    E_FINAL_TOUCH_RECEPTION_prix_cible
    E_FINAL_TOUCH_RECEPTION_Sigapp
    E_FINAL_TOUCH_RECEPTION_GAP
    E_FINAL_TOUCH_RECEPTION_Interne
    E_FINAL_TOUCH_RECEPTION_Sem
    E_FINAL_TOUCH_RECEPTION_Manager_DA
End Enum


Public Enum E_GREEN_LIGHT
    E_GREEN_LIGHT_Reference = 1
    E_GREEN_LIGHT_designation
    E_GREEN_LIGHT_QUANTITE_theorique
    E_GREEN_LIGHT_QUANTITE_confirmee
    E_GREEN_LIGHT_ECHANCIER_ONL_semaine
    E_GREEN_LIGHT_cofor
    E_GREEN_LIGHT_NOM_fournisseur
    E_GREEN_LIGHT_prog_livraison
    E_GREEN_LIGHT_numero_contrat
    E_GREEN_LIGHT_NOM_appro
    E_GREEN_LIGHT_Tel_appro
    E_GREEN_LIGHT_mail_appro
    E_GREEN_LIGHT_Nom_contact_log
    E_GREEN_LIGHT_Tel_contact_log
    E_GREEN_LIGHT_mail_contact_log
    E_GREEN_LIGHT_tmc
    E_GREEN_LIGHT_PRE_SERIAL_PRICE_YPRS_contract
    E_GREEN_LIGHT_INITIAL_SERIAL_PRICE
    E_GREEN_LIGHT_RATE_PRE_SERIAL_div_INIT_PRICE
    E_GREEN_LIGHT_OKNOK
    E_GREEN_LIGHT_TANGO_PRICE
    E_GREEN_LIGHT_TANGO_RATE
    E_GREEN_LIGHT_TANGO_OKNOK
    E_GREEN_LIGHT_MANAGER
    E_GREEN_LIGHT_Spending_sigapp
    E_GREEN_LIGHT_Spending_Target
    E_GREEN_LIGHT_Gap
    E_GREEN_LIGHT_rate
    E_GREEN_LIGHT_IS_INTERNAL
    E_GREEN_LIGHT_WITH_INDEX
    E_GREEN_LIGHT_IS_IN_TANGO
    ' new data
    E_GREEN_LIGHT_DOMAIN
    E_GREEN_LIGHT_RU
    E_GREEN_LIGHT_DIV
End Enum



Public Enum E_RECEPTION_REPORT_STEP
    E_RECEPTION_REPORT_STEP_GET_DATA_FROM_MB51
    E_RECEPTION_REPORT_STEP_GET_INTERNAL_SUPPLIERS
    E_RECEPTION_REPORT_STEP_MATCH_WITH_INTERROCOM
    E_RECEPTION_REPORT_STEP_FINAL_TOUCH
End Enum



Public Enum E_MANAGERS_DA
    E_MANAGERS_DA_ARTICLE = 1
    E_MANAGERS_DA_ACHETEUR
    E_MANAGERS_DA_RU
End Enum


Public Enum E_ECHANCIER_ONL_semaine_SCENARIO
    E_ECHANCIER_ONL_semaine_SCENARIO_PU
    E_ECHANCIER_ONL_semaine_SCENARIO_DEL
End Enum


Public Enum E_PIVOT_STD
    E_PIVOT_ANGEL_STD
    E_PIVOT_CAROLINE_STD
End Enum
