Attribute VB_Name = "EnumModule"
Option Explicit

'The MIT License (MIT)
'
'Copyright (c) 2020 FORREST
' Mateusz Milewski mateusz.milewski@mpsa.com aka FORREST
'
'Permission is hereby granted, free of charge, to any person obtaining a copy
'of this software and associated documentation files (the "Software"), to deal
'in the Software without restriction, including without limitation the rights
'to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
'copies of the Software, and to permit persons to whom the Software is
'furnished to do so, subject to the following conditions:
'
'The above copyright notice and this permission notice shall be included in all
'copies or substantial portions of the Software.
'
'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
'IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
'FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
'AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
'LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
'OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
'SOFTWARE.
'
'
' THE EVO TOOL


Public Enum E_FILE_TYPE
    E_MASTER_PUS
    E_FEED_CPL
    E_TP04_01
    E_SQ01
End Enum

Public Enum E_MASTER_ORDER
    E_MASTER_Reference = 1
    E_MASTER_DESIGNATION
    E_MASTER_QTY
    E_MASTER_CQTY
    E_MASTER_ECHANCIER_ONL_S
    E_MASTER_cofor
    E_MASTER_Nom_fournisseur
    E_MASTER_prog_livraison
    E_MASTER_num_contrat
    E_MASTER_Nom_appro
    E_MASTER_Tel_appro
    E_MASTER_mail_appro
    E_MASTER_Nom_contact_log
    E_MASTER_Tel_contact_log
    E_MASTER_mail_contact_log
    E_MASTER_TMC
End Enum

Public Enum E_MASTER_2_ORDER
    E_MASTER_2_COFOR_VENDEUR = 17
    E_MASTER_2_COFOR_EXPEDITEUR
    E_MASTER_2_NOM_FOURNISSEUR
    E_MASTER_2_ADDRESS_EXPEDITEUR_COMPLET
    E_MASTER_2_COFOR_HIBRIDE
    E_MASTER_2_Incoterm
    E_MASTER_2_TYPE_DE_PIECE
    E_MASTER_2_CONDI
    E_MASTER_2_UC
    E_MASTER_2_POIDS
    E_MASTER_2_LONGEUR
    E_MASTER_2_LARGEUR
    E_MASTER_2_HAUTEUR
    E_MASTER_2_VOLUME
    E_MASTER_2_HAZARDOUS
    E_MASTER_2_STACKABLE
    E_MASTER_2_ALT_condi
    E_MASTER_2_ALT_poids
    E_MASTER_2_Alt_longueur
    E_MASTER_2_Alt_largeur
    E_MASTER_2_Alt_hauteur
    E_MASTER_2_COFOR_GEFCO
    E_MASTER_2_AGENCE_GEFCO
    E_MASTER_2_CONTACT_AGENCE
    E_MASTER_2_nom_contact_transport
    E_MASTER_2_tel_contact_transport
    E_MASTER_2_mail_contact_transport
    E_MASTER_2_DHEF
    E_MASTER_2_DHAS
    E_MASTER_2_No_Ordenes
    E_MASTER_2_ROUTE
    E_MASTER_2_ML
End Enum


Public Enum E_FORM_SCENARIO_TYPE
    E_FORM_SCENARIO_COPY_PASTE = 1
    E_FORM_SCENARIO_CREATE_PIVOT_SCENARIO
    E_FORM_SCENARIO_KPI
    E_FORM_SCENATIO_PRICE_MATCHING_FOR_TP04
    E_FORM_SCENATIO_PRICE_MATCHING_FOR_SQ01
End Enum


Public Enum E_COPY_HANDLER_INIT
    E_COPY_HANDLER_COPY_ONE = 1
    E_COPY_HANDLER_BY_TMC_OPT
    E_COPY_HANDLER_FOR_PIVOT_CREATION
End Enum


Public Enum E_PIVOT_SRC
    E_PIVOT_SRC_ID = 1
    E_PIVOT_SRC_WIERSZ
    E_PIVOT_SRC_REF
    E_PIVOT_SRC_COFOR_VENDEUR
    E_PIVOT_SRC_COFOR_EXPEDITEUR
    E_PIVOT_SRC_SUPPLIER_NAME
    E_PIVOT_SRC_DELIVERY_DATE
    E_PIVOT_SRC_DELIVERY_YEAR
    E_PIVOT_SRC_DELIVERY_MONTH
    E_PIVOT_SRC_DELIVERY_WEEK
    E_PIVOT_SRC_DELIVERY_YYYYCW
    E_PIVOT_SRC_AK_COL_FROM_PLE
    E_PIVOT_SRC_ORDER_DATE
    E_PIVOT_SRC_ORDER_YEAR
    E_PIVOT_SRC_ORDER_MONTH
    E_PIVOT_SRC_ORDER_WEEK
    E_PIVOT_SRC_ORDER_YYYYCW
    E_PIVOT_SRC_ROUTE
    E_PIVOT_SRC_PILOT
    E_PIVOT_SRC_ROUTE_AND_PILOT
    E_PIVOT_SRC_QTY
    E_PIVOT_SRC_CQTY
    E_PIVOT_SRC_UC
    E_PIVOT_SRC_OQ
    E_PIVOT_SRC_COQ
    E_PIVOT_SRC_ROUNDUP_OQ1
    E_PIVOT_SRC_ROUNDUP_COQ1
    E_PIVOT_SRC_SUMIF_QTY
    E_PIVOT_SRC_SUMIF_CQTY
    E_PIVOT_SRC_SUMIF_UC
    E_PIVOT_SRC_SUMIF_OQ
    E_PIVOT_SRC_SUMIF_COQ
    E_PIVOT_SRC_CONDI
    E_PIVOT_SRC_UA_PC_GV
    E_PIVOT_SRC_UA_BPC
    E_PIVOT_SRC_UA_MC
    E_PIVOT_SRC_UA_MBU
    E_PIVOT_SRC_UA_MAX_CAPACITY
    E_PIVOT_SRC__TN_ML
    E_PIVOT_SRC__CONFIRMED_TN_ML
    E_PIVOT_SRC__LQ
    E_PIVOT_SRC__CLQ
    E_PIVOT_SRC__RP
    E_PIVOT_SRC__CRP
    E_PIVOT_SRC__TN_box_ML
    E_PIVOT_SRC__CONFIRMED_TN_box_ML
    E_PIVOT_SRC__RN_ML
    E_PIVOT_SRC__CONFIRMED_RN_ML
    E_PIVOT_SRC__ROUNDUP_RN_ML
    E_PIVOT_SRC__ROUNDUP_CONFIRMED_RN_ML
    E_PIVOT_SRC___SHORT_ORDER_DATE
    E_PIVOT_SRC___SHORT_DEL_DATE
    E_PIVOT_SRC____TYPE_DE_PIECE
    E_PIVOT_SRC____CLOE_COL_E_PRICE
End Enum


Public Enum E_PIVOT_PROXY2
    E_PIVOT_PROXY2_ID = 1
    E_PIVOT_PROXY2_WIERSZ
    E_PIVOT_PROXY2_REF
    E_PIVOT_PROXY2_COFOR_VENDEUR
    E_PIVOT_PROXY2_COFOR_EXPEDITEUR
    E_PIVOT_PROXY2_SUPPLIER_NAME
    E_PIVOT_PROXY2_DELIVERY_DATE
    E_PIVOT_PROXY2_DELIVERY_YEAR
    E_PIVOT_PROXY2_DELIVERY_MONTH
    E_PIVOT_PROXY2_DELIVERY_WEEK
    E_PIVOT_PROXY2_DELIVERY_YYYYCW
    E_PIVOT_PROXY2_AK_COL_FROM_PLE
    E_PIVOT_PROXY2_ORDER_DATE
    E_PIVOT_PROXY2_ORDER_YEAR
    E_PIVOT_PROXY2_ORDER_MONTH
    E_PIVOT_PROXY2_ORDER_WEEK
    E_PIVOT_PROXY2_ORDER_YYYYCW
    E_PIVOT_PROXY2_ROUTE_AND_PILOT
    E_PIVOT_PROXY2_SUMIF_QTY
    E_PIVOT_PROXY2_SUMIF_CQTY
    E_PIVOT_PROXY2_SUMIF_UC
    E_PIVOT_PROXY2_SUMIF_OQ
    E_PIVOT_PROXY2_SUMIF_COQ
    E_PIVOT_PROXY2_CONDI
    E_PIVOT_PROXY2_UA_PC_GV
    E_PIVOT_PROXY2_UA_BPC
    E_PIVOT_PROXY2_UA_MC
    E_PIVOT_PROXY2_UA_MBU
    E_PIVOT_PROXY2_UA_MAX_CAPACITY
    E_PIVOT_PROXY2__TN_ML
    E_PIVOT_PROXY2__CONFIRMED_TN_ML
    E_PIVOT_PROXY2__LQ
    E_PIVOT_PROXY2__CLQ
    E_PIVOT_PROXY2__RP
    E_PIVOT_PROXY2__CRP
    E_PIVOT_PROXY2__TN_box_ML
    E_PIVOT_PROXY2__CONFIRMED_TN_box_ML
    E_PIVOT_PROXY2__RN_ML
    E_PIVOT_PROXY2__CONFIRMED_RN_ML
    E_PIVOT_PROXY2__ROUNDUP_RN_ML
    E_PIVOT_PROXY2__ROUNDUP_CONFIRMED_RN_ML
    E_PIVOT_PROXY2___SHORT_ORDER_DATE
    E_PIVOT_PROXY2___SHORT_DEL_DATE
    E_PIVOT_PROXY2____TYPE_DE_PIECE
    E_PIVOT_PROXY2____CLOE_COL_E_PRICE
End Enum



Public Enum E_KPI_SRC
    E_KPI_SRC_REF = 1
    E_KPI_SRC_V_COFOR
    E_KPI_SRC_E_COFOR
    E_KPI_SRC_SUPPLIER_NAME
    E_KPI_SRC_DAP
    E_KPI_SRC_NO_DATA
    E_KPI_SRC_TYPE_DE_PIECE
    E_KPI_SRC_UA
    E_KPI_SRC_PLE
    E_KPI_SRC_GREEN
    E_KPI_SRC_BLUE
    E_KPI_SRC_YELLOW
End Enum






Public Enum E_TP04_OUTPUT_REP_PART
    E_TP04_OUTPUT_REP_PART_PRESERIAL = E_MASTER_TMC + 1
    E_TP04_OUTPUT_REP_PART_INIT_SERIAL_PRICE
    E_TP04_OUTPUT_REP_PART_RATE
    E_TP04_OUTPUT_REP_PART_OKNOK
End Enum


Public Enum E_SQ01_CONFIG
    E_SQ01_CONFIG_MAKE_ALL
    E_SQ01_CONFIG_START_FROM_PASTING_ALREADY_PREPARED_INPUT_LIST
End Enum

'TP04_01

Public Enum E_TP04_01
    E_TP04_01_DOMAINE = 1
    E_TP04_01_ARTICLE
    E_TP04_01_REPERE_UTI
    E_TP04_01_DOC_ACHAT
    E_TP04_01_POSTE
    E_TP04_01_TYPE
    E_TP04_01_DIV
    E_TP04_01_FOUR
    E_TP04_01_DATE_DEBUT
    E_TP04_01_DATE_FIN
    E_TP04_01_UNITE_DE_PRIX
    E_TP04_01_PRIX
    E_TP04_01_UNITE
    E_TP04_01_DEV
End Enum

Public Enum E_FROM_SQ01_QUASI_TP04
    E_FROM_SQ01_QUASI_TP04_DOMAIN = 1
    E_FROM_SQ01_QUASI_TP04_ARTICLE
    E_FROM_SQ01_QUASI_TP04_RU
    E_FROM_SQ01_QUASI_TP04_DOC_ACHAT
    E_FROM_SQ01_QUASI_TP04_POSTE
    E_FROM_SQ01_QUASI_TP04_TYPE
    E_FROM_SQ01_QUASI_TP04_DIV
    E_FROM_SQ01_QUASI_TP04_FOUR
    E_FROM_SQ01_QUASI_TP04_DATE_DEBUT
    E_FROM_SQ01_QUASI_TP04_DATE_FIN
    E_FROM_SQ01_QUASI_TP04_UNITE
    E_FROM_SQ01_QUASI_TP04_SUM
    E_FROM_SQ01_QUASI_TP04_UNITE2_EMPTY
    E_FROM_SQ01_QUASI_TP04_CURRENCY
End Enum


Public Enum E_SQ01_PREDEF
    E_SQ01_PREDEF_SYSTEM
    E_SQ01_PREDEF_LIST1
    E_SQ01_PREDEF_STD1
    E_SQ01_PREDEF_LIST2
    E_SQ01_PREDEF_STD2
End Enum
